# Generated by Django 4.0.4 on 2022-05-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.TextField(null=True, verbose_name='头像URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=1024, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='0', max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='是否员工'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=1024, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.TextField(unique=True, verbose_name='用户名(openid)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_key',
            field=models.TextField(default='', verbose_name='session值'),
        ),
    ]
