# Generated by Django 4.0.4 on 2022-06-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='history',
            table='history',
        ),
    ]
