# Generated by Django 4.0.4 on 2022-06-16 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objModel', '0006_alter_category_options_alter_objmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0002_alter_history_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('created_by', 'obj_model')},
        ),
    ]
