# Generated by Django 4.0.4 on 2022-06-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_history_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='view_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
