# Generated by Django 4.0.4 on 2022-06-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_history_view_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='history',
            name='view_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
