# Generated by Django 4.0.4 on 2022-05-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objModel', '0002_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='objmodel',
            name='file_type',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='objmodel',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
