# Generated by Django 4.0.4 on 2022-05-03 10:53

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('objModel', '0003_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objmodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='objmodel',
            name='model_dir_id',
        ),
        migrations.AddField(
            model_name='objmodel',
            name='file_dir_id',
            field=models.CharField(default='default', max_length=32),
        ),
        migrations.AddField(
            model_name='objmodel',
            name='model_file',
            field=models.FileField(default='default\\default.obj', upload_to=utils.utils.upload_dir),
        ),
        migrations.AlterField(
            model_name='objmodel',
            name='cover',
            field=models.ImageField(default='default\\default.png', height_field=400, upload_to=utils.utils.upload_dir, width_field=600),
        ),
    ]
