# Generated by Django 4.0.4 on 2022-05-03 12:17

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('objModel', '0004_remove_objmodel_file_remove_objmodel_model_dir_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objmodel',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='objmodel',
            name='cover',
            field=models.ImageField(default='default\\default.png', upload_to=utils.utils.upload_obj_cover_dir),
        ),
    ]
