# Generated by Django 4.0.4 on 2022-06-21 07:03

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('objModel', '0006_alter_category_options_alter_objmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objmodel',
            name='file_type',
            field=models.CharField(max_length=16, null=True, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='objmodel',
            name='model_file',
            field=models.FileField(default='default\\default.obj', null=True, upload_to=utils.utils.upload_obj_model_dir, verbose_name='模型文件'),
        ),
    ]
